/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen;


import org.jooq.ForeignKey;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.QOM.ForeignKeyRule;
import org.lower.document.jooq.codegen.tables.Clients;
import org.lower.document.jooq.codegen.tables.Databasechangeloglock;
import org.lower.document.jooq.codegen.tables.Documents;
import org.lower.document.jooq.codegen.tables.Owners;
import org.lower.document.jooq.codegen.tables.Staffs;
import org.lower.document.jooq.codegen.tables.Users;
import org.lower.document.jooq.codegen.tables.records.ClientsRecord;
import org.lower.document.jooq.codegen.tables.records.DatabasechangeloglockRecord;
import org.lower.document.jooq.codegen.tables.records.DocumentsRecord;
import org.lower.document.jooq.codegen.tables.records.OwnersRecord;
import org.lower.document.jooq.codegen.tables.records.StaffsRecord;
import org.lower.document.jooq.codegen.tables.records.UsersRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ClientsRecord> CLIENTS_PKEY = Internal.createUniqueKey(Clients.CLIENTS, DSL.name("clients_pkey"), new TableField[] { Clients.CLIENTS.ID }, true);
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, DSL.name("databasechangeloglock_pkey"), new TableField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
    public static final UniqueKey<DocumentsRecord> DOCUMENTS_PKEY = Internal.createUniqueKey(Documents.DOCUMENTS, DSL.name("documents_pkey"), new TableField[] { Documents.DOCUMENTS.ID }, true);
    public static final UniqueKey<OwnersRecord> OWNERS_PKEY = Internal.createUniqueKey(Owners.OWNERS, DSL.name("owners_pkey"), new TableField[] { Owners.OWNERS.ID }, true);
    public static final UniqueKey<StaffsRecord> STAFFS_PKEY = Internal.createUniqueKey(Staffs.STAFFS, DSL.name("staffs_pkey"), new TableField[] { Staffs.STAFFS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_USERNAME_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_username_key"), new TableField[] { Users.USERS.USERNAME }, true);

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<DocumentsRecord, ClientsRecord> DOCUMENTS__DOCUMENTS_CLIENT_ID_FKEY = Internal.createForeignKey(Documents.DOCUMENTS, DSL.name("documents_client_id_fkey"), new TableField[] { Documents.DOCUMENTS.CLIENT_ID }, Keys.CLIENTS_PKEY, new TableField[] { Clients.CLIENTS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<DocumentsRecord, UsersRecord> DOCUMENTS__DOCUMENTS_USER_ID_FKEY = Internal.createForeignKey(Documents.DOCUMENTS, DSL.name("documents_user_id_fkey"), new TableField[] { Documents.DOCUMENTS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<OwnersRecord, UsersRecord> OWNERS__OWNERS_USER_ID_FKEY = Internal.createForeignKey(Owners.OWNERS, DSL.name("owners_user_id_fkey"), new TableField[] { Owners.OWNERS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<StaffsRecord, OwnersRecord> STAFFS__STAFFS_OWNER_ID_FKEY = Internal.createForeignKey(Staffs.STAFFS, DSL.name("staffs_owner_id_fkey"), new TableField[] { Staffs.STAFFS.OWNER_ID }, Keys.OWNERS_PKEY, new TableField[] { Owners.OWNERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
    public static final ForeignKey<StaffsRecord, UsersRecord> STAFFS__STAFFS_USER_ID_FKEY = Internal.createForeignKey(Staffs.STAFFS, DSL.name("staffs_user_id_fkey"), new TableField[] { Staffs.STAFFS.USER_ID }, Keys.USERS_PKEY, new TableField[] { Users.USERS.ID }, true, ForeignKeyRule.CASCADE, ForeignKeyRule.NO_ACTION);
}
