/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;
import org.lower.document.jooq.codegen.tables.Clients;
import org.lower.document.jooq.codegen.tables.CourtDecisions;
import org.lower.document.jooq.codegen.tables.CourtOrgs;
import org.lower.document.jooq.codegen.tables.Databasechangelog;
import org.lower.document.jooq.codegen.tables.Databasechangeloglock;
import org.lower.document.jooq.codegen.tables.Documents;
import org.lower.document.jooq.codegen.tables.Owners;
import org.lower.document.jooq.codegen.tables.PgpArmorHeaders;
import org.lower.document.jooq.codegen.tables.RecipientOrgs;
import org.lower.document.jooq.codegen.tables.Staffs;
import org.lower.document.jooq.codegen.tables.Users;
import org.lower.document.jooq.codegen.tables.records.PgpArmorHeadersRecord;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.clients</code>.
     */
    public final Clients CLIENTS = Clients.CLIENTS;

    /**
     * Таблица судебных решений по делам о банкротстве
     */
    public final CourtDecisions COURT_DECISIONS = CourtDecisions.COURT_DECISIONS;

    /**
     * The table <code>public.court_orgs</code>.
     */
    public final CourtOrgs COURT_ORGS = CourtOrgs.COURT_ORGS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.documents</code>.
     */
    public final Documents DOCUMENTS = Documents.DOCUMENTS;

    /**
     * The table <code>public.owners</code>.
     */
    public final Owners OWNERS = Owners.OWNERS;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(org.lower.document.jooq.codegen.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return org.lower.document.jooq.codegen.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return org.lower.document.jooq.codegen.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>public.recipient_orgs</code>.
     */
    public final RecipientOrgs RECIPIENT_ORGS = RecipientOrgs.RECIPIENT_ORGS;

    /**
     * The table <code>public.staffs</code>.
     */
    public final Staffs STAFFS = Staffs.STAFFS;

    /**
     * The table <code>public.users</code>.
     */
    public final Users USERS = Users.USERS;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Clients.CLIENTS,
            CourtDecisions.COURT_DECISIONS,
            CourtOrgs.COURT_ORGS,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Documents.DOCUMENTS,
            Owners.OWNERS,
            PgpArmorHeaders.PGP_ARMOR_HEADERS,
            RecipientOrgs.RECIPIENT_ORGS,
            Staffs.STAFFS,
            Users.USERS
        );
    }
}
