/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen;


import org.jooq.Configuration;
import org.jooq.Field;
import org.jooq.Result;
import org.lower.document.jooq.codegen.tables.*;
import org.lower.document.jooq.codegen.tables.records.PgpArmorHeadersRecord;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.clients</code>.
     */
    public static final Clients CLIENTS = Clients.CLIENTS;

    /**
     * Таблица судебных решений по делам о банкротстве
     */
    public static final CourtDecisions COURT_DECISIONS = CourtDecisions.COURT_DECISIONS;

    /**
     * The table <code>public.court_orgs</code>.
     */
    public static final CourtOrgs COURT_ORGS = CourtOrgs.COURT_ORGS;

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.documents</code>.
     */
    public static final Documents DOCUMENTS = Documents.DOCUMENTS;

    /**
     * The table <code>public.owners</code>.
     */
    public static final Owners OWNERS = Owners.OWNERS;

    /**
     * The table <code>public.pgp_armor_headers</code>.
     */
    public static final PgpArmorHeaders PGP_ARMOR_HEADERS = PgpArmorHeaders.PGP_ARMOR_HEADERS;

    /**
     * Call <code>public.pgp_armor_headers</code>.
     */
    public static Result<PgpArmorHeadersRecord> PGP_ARMOR_HEADERS(
          Configuration configuration
        , String __1
    ) {
        return configuration.dsl().selectFrom(org.lower.document.jooq.codegen.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
              __1
        )).fetch();
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          String __1
    ) {
        return org.lower.document.jooq.codegen.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * Get <code>public.pgp_armor_headers</code> as a table.
     */
    public static PgpArmorHeaders PGP_ARMOR_HEADERS(
          Field<String> __1
    ) {
        return org.lower.document.jooq.codegen.tables.PgpArmorHeaders.PGP_ARMOR_HEADERS.call(
            __1
        );
    }

    /**
     * The table <code>public.recipient_orgs</code>.
     */
    public static final RecipientOrgs RECIPIENT_ORGS = RecipientOrgs.RECIPIENT_ORGS;

    /**
     * The table <code>public.staffs</code>.
     */
    public static final Staffs STAFFS = Staffs.STAFFS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
