/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.routines;


import java.util.UUID;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.lower.document.jooq.codegen.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenRandomUuidV7 extends AbstractRoutine<UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.gen_random_uuid_v7.RETURN_VALUE</code>.
     */
    public static final Parameter<UUID> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.UUID, false);

    /**
     * Create a new routine call instance
     */
    public GenRandomUuidV7() {
        super("gen_random_uuid_v7", Public.PUBLIC, DSL.comment(""), SQLDataType.UUID);

        setReturnParameter(RETURN_VALUE);
    }
}
