/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.lower.document.jooq.codegen.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PgpArmorHeaders extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>public.pgp_armor_headers._1</code>.
     */
    public static final Parameter<String> _1 = Internal.createParameter("_1", SQLDataType.CLOB, true);

    /**
     * The parameter <code>public.pgp_armor_headers.key</code>.
     */
    public static final Parameter<String> KEY = Internal.createParameter("key", SQLDataType.CLOB, false);

    /**
     * The parameter <code>public.pgp_armor_headers.value</code>.
     */
    public static final Parameter<String> VALUE = Internal.createParameter("value", SQLDataType.CLOB, false);

    /**
     * Create a new routine call instance
     */
    public PgpArmorHeaders() {
        super("pgp_armor_headers", Public.PUBLIC, DSL.comment(""));

        addInParameter(_1);
        addOutParameter(KEY);
        addOutParameter(VALUE);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(String value) {
        setValue(_1, value);
    }

    /**
     * Get the <code>key</code> parameter OUT value from the routine
     */
    public String getKey() {
        return get(KEY);
    }

    /**
     * Get the <code>value</code> parameter OUT value from the routine
     */
    public String getValue() {
        return get(VALUE);
    }
}
