spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5015/lower_db}
    username: ${USER_NAME:lower_user}
    password: ${USER_PASSWORD:lowerpassword}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 200
      minimum-idle: 5
  jooq:
    sql-dialect: POSTGRES
  mail:
    host: ${MAIL_HOST:smtp.yandex.ru}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:igarik10@yandex.ru}
    password: ${MAIL_PASSWORD:pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:false}
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    time-zone: Europe/Moscow
    date-format: yyyy-MM-dd HH:mm:ss

logging:
  level:
    org.jooq: WARN

name-declension:
  grpc:
    host: ${GRPC_IP:localhost}
    port: 50051
    plaintext: true
    deadline-millis: 5000

app:
  jwt:
    secret: ${JWT_SECRET} # ПЕРЕМЕННАЯ ОКРУЖЕНИЯ, ДЕФАУЛТ СТРОГО ЛОКАЛЬНО!!!!!
    expiration-hours: 12

  admin:
    name: ${ADMIN}