/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables.records;


import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lower.document.jooq.codegen.tables.Clients;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ClientsRecord extends UpdatableRecordImpl<ClientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.clients.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.clients.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.clients.full_name</code>.
     */
    public void setFullName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.clients.full_name</code>.
     */
    public String getFullName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.clients.birth_date</code>.
     */
    public void setBirthDate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.clients.birth_date</code>.
     */
    public LocalDate getBirthDate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>public.clients.birth_place</code>.
     */
    public void setBirthPlace(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.clients.birth_place</code>.
     */
    public String getBirthPlace() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.clients.inn</code>.
     */
    public void setInn(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.clients.inn</code>.
     */
    public String getInn() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.clients.snils</code>.
     */
    public void setSnils(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.clients.snils</code>.
     */
    public String getSnils() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.clients.address</code>.
     */
    public void setAddress(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.clients.address</code>.
     */
    public String getAddress() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.clients.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.clients.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.clients.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.clients.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClientsRecord
     */
    public ClientsRecord() {
        super(Clients.CLIENTS);
    }

    /**
     * Create a detached, initialised ClientsRecord
     */
    public ClientsRecord(UUID id, String fullName, LocalDate birthDate, String birthPlace, String inn, String snils, String address, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Clients.CLIENTS);

        setId(id);
        setFullName(fullName);
        setBirthDate(birthDate);
        setBirthPlace(birthPlace);
        setInn(inn);
        setSnils(snils);
        setAddress(address);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
