/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lower.document.jooq.codegen.tables.CourtDecisions;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * Таблица судебных решений по делам о банкротстве
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CourtDecisionsRecord extends UpdatableRecordImpl<CourtDecisionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.court_decisions.id</code>. Уникальный
     * идентификатор записи
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.court_decisions.id</code>. Уникальный
     * идентификатор записи
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.court_decisions.owner_id</code>. ID финансового
     * управляющего (владельца дела)
     */
    public void setOwnerId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.court_decisions.owner_id</code>. ID финансового
     * управляющего (владельца дела)
     */
    public UUID getOwnerId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.court_decisions.client_id</code>. ID клиента
     * (должника)
     */
    public void setClientId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.court_decisions.client_id</code>. ID клиента
     * (должника)
     */
    public UUID getClientId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.court_decisions.court_name</code>. Наименование
     * суда в родительном падеже (например: "Арбитражного суда Ростовской
     * области")
     */
    public void setCourtName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.court_decisions.court_name</code>. Наименование
     * суда в родительном падеже (например: "Арбитражного суда Ростовской
     * области")
     */
    public String getCourtName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.court_decisions.decision_date</code>. Дата
     * вынесения решения о признании банкротом
     */
    public void setDecisionDate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.court_decisions.decision_date</code>. Дата
     * вынесения решения о признании банкротом
     */
    public LocalDate getDecisionDate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>public.court_decisions.case_number</code>. Номер дела о
     * банкротстве (например: "А53-10291/2023")
     */
    public void setCaseNumber(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.court_decisions.case_number</code>. Номер дела о
     * банкротстве (например: "А53-10291/2023")
     */
    public String getCaseNumber() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.court_decisions.created_at</code>. Дата и время
     * создания записи
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.court_decisions.created_at</code>. Дата и время
     * создания записи
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>public.court_decisions.updated_at</code>. Дата и время
     * последнего обновления записи
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.court_decisions.updated_at</code>. Дата и время
     * последнего обновления записи
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourtDecisionsRecord
     */
    public CourtDecisionsRecord() {
        super(CourtDecisions.COURT_DECISIONS);
    }

    /**
     * Create a detached, initialised CourtDecisionsRecord
     */
    public CourtDecisionsRecord(UUID id, UUID ownerId, UUID clientId, String courtName, LocalDate decisionDate, String caseNumber, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(CourtDecisions.COURT_DECISIONS);

        setId(id);
        setOwnerId(ownerId);
        setClientId(clientId);
        setCourtName(courtName);
        setDecisionDate(decisionDate);
        setCaseNumber(caseNumber);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
