/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lower.document.jooq.codegen.tables.CourtOrgs;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CourtOrgsRecord extends UpdatableRecordImpl<CourtOrgsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.court_orgs.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.court_orgs.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.court_orgs.doc_type</code>.
     */
    public void setDocType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.court_orgs.doc_type</code>.
     */
    public String getDocType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.court_orgs.region_code</code>.
     */
    public void setRegionCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.court_orgs.region_code</code>.
     */
    public String getRegionCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.court_orgs.org_name</code>.
     */
    public void setOrgName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.court_orgs.org_name</code>.
     */
    public String getOrgName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.court_orgs.org_address</code>.
     */
    public void setOrgAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.court_orgs.org_address</code>.
     */
    public String getOrgAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.court_orgs.org_note</code>.
     */
    public void setOrgNote(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.court_orgs.org_note</code>.
     */
    public String getOrgNote() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.court_orgs.is_active</code>.
     */
    public void setIsActive(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.court_orgs.is_active</code>.
     */
    public Boolean getIsActive() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.court_orgs.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.court_orgs.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.court_orgs.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.court_orgs.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CourtOrgsRecord
     */
    public CourtOrgsRecord() {
        super(CourtOrgs.COURT_ORGS);
    }

    /**
     * Create a detached, initialised CourtOrgsRecord
     */
    public CourtOrgsRecord(UUID id, String docType, String regionCode, String orgName, String orgAddress, String orgNote, Boolean isActive, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(CourtOrgs.COURT_ORGS);

        setId(id);
        setDocType(docType);
        setRegionCode(regionCode);
        setOrgName(orgName);
        setOrgAddress(orgAddress);
        setOrgNote(orgNote);
        setIsActive(isActive);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
