/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lower.document.jooq.codegen.tables.Documents;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DocumentsRecord extends UpdatableRecordImpl<DocumentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.documents.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.documents.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.documents.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.documents.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.documents.client_id</code>.
     */
    public void setClientId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.documents.client_id</code>.
     */
    public UUID getClientId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>public.documents.template_type</code>.
     */
    public void setTemplateType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.documents.template_type</code>.
     */
    public String getTemplateType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.documents.metadata</code>.
     */
    public void setMetadata(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.documents.metadata</code>.
     */
    public JSONB getMetadata() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.documents.content</code>.
     */
    public void setContent(byte[] value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.documents.content</code>.
     */
    public byte[] getContent() {
        return (byte[]) get(5);
    }

    /**
     * Setter for <code>public.documents.size_kb</code>.
     */
    public void setSizeKb(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.documents.size_kb</code>.
     */
    public Integer getSizeKb() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.documents.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.documents.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(7);
    }

    /**
     * Setter for <code>public.documents.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.documents.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DocumentsRecord
     */
    public DocumentsRecord() {
        super(Documents.DOCUMENTS);
    }

    /**
     * Create a detached, initialised DocumentsRecord
     */
    public DocumentsRecord(UUID id, UUID userId, UUID clientId, String templateType, JSONB metadata, byte[] content, Integer sizeKb, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Documents.DOCUMENTS);

        setId(id);
        setUserId(userId);
        setClientId(clientId);
        setTemplateType(templateType);
        setMetadata(metadata);
        setContent(content);
        setSizeKb(sizeKb);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
