/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lower.document.jooq.codegen.tables.Owners;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OwnersRecord extends UpdatableRecordImpl<OwnersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.owners.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.owners.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.owners.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.owners.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.owners.full_name</code>.
     */
    public void setFullName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.owners.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.owners.full_name_short</code>.
     */
    public void setFullNameShort(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.owners.full_name_short</code>.
     */
    public String getFullNameShort() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.owners.mail_address</code>.
     */
    public void setMailAddress(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.owners.mail_address</code>.
     */
    public String getMailAddress() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.owners.email</code>.
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.owners.email</code>.
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.owners.sro_name</code>.
     */
    public void setSroName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.owners.sro_name</code>.
     */
    public String getSroName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.owners.sro_inn</code>.
     */
    public void setSroInn(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.owners.sro_inn</code>.
     */
    public String getSroInn() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.owners.sro_ogrn</code>.
     */
    public void setSroOgrn(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.owners.sro_ogrn</code>.
     */
    public String getSroOgrn() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.owners.sro_address</code>.
     */
    public void setSroAddress(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.owners.sro_address</code>.
     */
    public String getSroAddress() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.owners.user_inn</code>.
     */
    public void setUserInn(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.owners.user_inn</code>.
     */
    public String getUserInn() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.owners.user_snils</code>.
     */
    public void setUserSnils(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.owners.user_snils</code>.
     */
    public String getUserSnils() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.owners.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.owners.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(12);
    }

    /**
     * Setter for <code>public.owners.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.owners.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OwnersRecord
     */
    public OwnersRecord() {
        super(Owners.OWNERS);
    }

    /**
     * Create a detached, initialised OwnersRecord
     */
    public OwnersRecord(UUID id, UUID userId, String fullName, String fullNameShort, String mailAddress, String email, String sroName, String sroInn, String sroOgrn, String sroAddress, String userInn, String userSnils, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Owners.OWNERS);

        setId(id);
        setUserId(userId);
        setFullName(fullName);
        setFullNameShort(fullNameShort);
        setMailAddress(mailAddress);
        setEmail(email);
        setSroName(sroName);
        setSroInn(sroInn);
        setSroOgrn(sroOgrn);
        setSroAddress(sroAddress);
        setUserInn(userInn);
        setUserSnils(userSnils);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
