/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lower.document.jooq.codegen.tables.RecipientOrgs;

import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecipientOrgsRecord extends UpdatableRecordImpl<RecipientOrgsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.recipient_orgs.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.recipient_orgs.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.recipient_orgs.doc_type</code>.
     */
    public void setDocType(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.recipient_orgs.doc_type</code>.
     */
    public String getDocType() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.recipient_orgs.org_name</code>.
     */
    public void setOrgName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.recipient_orgs.org_name</code>.
     */
    public String getOrgName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.recipient_orgs.org_address</code>.
     */
    public void setOrgAddress(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.recipient_orgs.org_address</code>.
     */
    public String getOrgAddress() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.recipient_orgs.org_note</code>.
     */
    public void setOrgNote(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.recipient_orgs.org_note</code>.
     */
    public String getOrgNote() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RecipientOrgsRecord
     */
    public RecipientOrgsRecord() {
        super(RecipientOrgs.RECIPIENT_ORGS);
    }

    /**
     * Create a detached, initialised RecipientOrgsRecord
     */
    public RecipientOrgsRecord(UUID id, String docType, String orgName, String orgAddress, String orgNote) {
        super(RecipientOrgs.RECIPIENT_ORGS);

        setId(id);
        setDocType(docType);
        setOrgName(orgName);
        setOrgAddress(orgAddress);
        setOrgNote(orgNote);
        resetTouchedOnNotNull();
    }
}
