/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables.records;


import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.lower.document.jooq.codegen.tables.Staffs;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class StaffsRecord extends UpdatableRecordImpl<StaffsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.staffs.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.staffs.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.staffs.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.staffs.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.staffs.full_name</code>.
     */
    public void setFullName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.staffs.full_name</code>.
     */
    public String getFullName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.staffs.full_name_short</code>.
     */
    public void setFullNameShort(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.staffs.full_name_short</code>.
     */
    public String getFullNameShort() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.staffs.email</code>.
     */
    public void setEmail(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.staffs.email</code>.
     */
    public String getEmail() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.staffs.user_inn</code>.
     */
    public void setUserInn(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.staffs.user_inn</code>.
     */
    public String getUserInn() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.staffs.user_snils</code>.
     */
    public void setUserSnils(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.staffs.user_snils</code>.
     */
    public String getUserSnils() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.staffs.owner_id</code>.
     */
    public void setOwnerId(UUID value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.staffs.owner_id</code>.
     */
    public UUID getOwnerId() {
        return (UUID) get(7);
    }

    /**
     * Setter for <code>public.staffs.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.staffs.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(8);
    }

    /**
     * Setter for <code>public.staffs.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.staffs.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StaffsRecord
     */
    public StaffsRecord() {
        super(Staffs.STAFFS);
    }

    /**
     * Create a detached, initialised StaffsRecord
     */
    public StaffsRecord(UUID id, UUID userId, String fullName, String fullNameShort, String email, String userInn, String userSnils, UUID ownerId, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(Staffs.STAFFS);

        setId(id);
        setUserId(userId);
        setFullName(fullName);
        setFullNameShort(fullNameShort);
        setEmail(email);
        setUserInn(userInn);
        setUserSnils(userSnils);
        setOwnerId(ownerId);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }
}
