/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.enums;


import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;
import org.lower.document.jooq.codegen.Public;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum RoleEnum implements EnumType {

    ADMIN("ADMIN"),

    OWNER("OWNER"),

    WORKER("WORKER");

    private final String literal;

    private RoleEnum(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "role_enum";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static RoleEnum lookupLiteral(String literal) {
        return EnumType.lookupLiteral(RoleEnum.class, literal);
    }
}
