// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

public interface CaseFormsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:namedeclension.CaseForms)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nominative = 1;</code>
   * @return The nominative.
   */
  java.lang.String getNominative();
  /**
   * <code>string nominative = 1;</code>
   * @return The bytes for nominative.
   */
  com.google.protobuf.ByteString
      getNominativeBytes();

  /**
   * <code>string genitive = 2;</code>
   * @return The genitive.
   */
  java.lang.String getGenitive();
  /**
   * <code>string genitive = 2;</code>
   * @return The bytes for genitive.
   */
  com.google.protobuf.ByteString
      getGenitiveBytes();

  /**
   * <code>string dative = 3;</code>
   * @return The dative.
   */
  java.lang.String getDative();
  /**
   * <code>string dative = 3;</code>
   * @return The bytes for dative.
   */
  com.google.protobuf.ByteString
      getDativeBytes();

  /**
   * <code>string accusative = 4;</code>
   * @return The accusative.
   */
  java.lang.String getAccusative();
  /**
   * <code>string accusative = 4;</code>
   * @return The bytes for accusative.
   */
  com.google.protobuf.ByteString
      getAccusativeBytes();

  /**
   * <code>string instrumental = 5;</code>
   * @return The instrumental.
   */
  java.lang.String getInstrumental();
  /**
   * <code>string instrumental = 5;</code>
   * @return The bytes for instrumental.
   */
  com.google.protobuf.ByteString
      getInstrumentalBytes();

  /**
   * <code>string prepositional = 6;</code>
   * @return The prepositional.
   */
  java.lang.String getPrepositional();
  /**
   * <code>string prepositional = 6;</code>
   * @return The bytes for prepositional.
   */
  com.google.protobuf.ByteString
      getPrepositionalBytes();
}
