// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

/**
 * Protobuf type {@code namedeclension.CaseForms}
 */
public final class CaseForms extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:namedeclension.CaseForms)
    CaseFormsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CaseForms.newBuilder() to construct.
  private CaseForms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CaseForms() {
    nominative_ = "";
    genitive_ = "";
    dative_ = "";
    accusative_ = "";
    instrumental_ = "";
    prepositional_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CaseForms();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_CaseForms_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_CaseForms_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.lower.document.grpc.proto.CaseForms.class, org.lower.document.grpc.proto.CaseForms.Builder.class);
  }

  public static final int NOMINATIVE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object nominative_ = "";
  /**
   * <code>string nominative = 1;</code>
   * @return The nominative.
   */
  @java.lang.Override
  public java.lang.String getNominative() {
    java.lang.Object ref = nominative_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      nominative_ = s;
      return s;
    }
  }
  /**
   * <code>string nominative = 1;</code>
   * @return The bytes for nominative.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNominativeBytes() {
    java.lang.Object ref = nominative_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      nominative_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GENITIVE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object genitive_ = "";
  /**
   * <code>string genitive = 2;</code>
   * @return The genitive.
   */
  @java.lang.Override
  public java.lang.String getGenitive() {
    java.lang.Object ref = genitive_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      genitive_ = s;
      return s;
    }
  }
  /**
   * <code>string genitive = 2;</code>
   * @return The bytes for genitive.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGenitiveBytes() {
    java.lang.Object ref = genitive_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      genitive_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DATIVE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dative_ = "";
  /**
   * <code>string dative = 3;</code>
   * @return The dative.
   */
  @java.lang.Override
  public java.lang.String getDative() {
    java.lang.Object ref = dative_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dative_ = s;
      return s;
    }
  }
  /**
   * <code>string dative = 3;</code>
   * @return The bytes for dative.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDativeBytes() {
    java.lang.Object ref = dative_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dative_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCUSATIVE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object accusative_ = "";
  /**
   * <code>string accusative = 4;</code>
   * @return The accusative.
   */
  @java.lang.Override
  public java.lang.String getAccusative() {
    java.lang.Object ref = accusative_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      accusative_ = s;
      return s;
    }
  }
  /**
   * <code>string accusative = 4;</code>
   * @return The bytes for accusative.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAccusativeBytes() {
    java.lang.Object ref = accusative_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      accusative_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INSTRUMENTAL_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object instrumental_ = "";
  /**
   * <code>string instrumental = 5;</code>
   * @return The instrumental.
   */
  @java.lang.Override
  public java.lang.String getInstrumental() {
    java.lang.Object ref = instrumental_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      instrumental_ = s;
      return s;
    }
  }
  /**
   * <code>string instrumental = 5;</code>
   * @return The bytes for instrumental.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInstrumentalBytes() {
    java.lang.Object ref = instrumental_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      instrumental_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREPOSITIONAL_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object prepositional_ = "";
  /**
   * <code>string prepositional = 6;</code>
   * @return The prepositional.
   */
  @java.lang.Override
  public java.lang.String getPrepositional() {
    java.lang.Object ref = prepositional_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prepositional_ = s;
      return s;
    }
  }
  /**
   * <code>string prepositional = 6;</code>
   * @return The bytes for prepositional.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPrepositionalBytes() {
    java.lang.Object ref = prepositional_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prepositional_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nominative_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nominative_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genitive_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, genitive_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dative_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dative_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accusative_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, accusative_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instrumental_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, instrumental_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prepositional_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, prepositional_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(nominative_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nominative_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(genitive_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, genitive_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dative_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dative_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(accusative_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, accusative_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(instrumental_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, instrumental_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(prepositional_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, prepositional_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.lower.document.grpc.proto.CaseForms)) {
      return super.equals(obj);
    }
    org.lower.document.grpc.proto.CaseForms other = (org.lower.document.grpc.proto.CaseForms) obj;

    if (!getNominative()
        .equals(other.getNominative())) return false;
    if (!getGenitive()
        .equals(other.getGenitive())) return false;
    if (!getDative()
        .equals(other.getDative())) return false;
    if (!getAccusative()
        .equals(other.getAccusative())) return false;
    if (!getInstrumental()
        .equals(other.getInstrumental())) return false;
    if (!getPrepositional()
        .equals(other.getPrepositional())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NOMINATIVE_FIELD_NUMBER;
    hash = (53 * hash) + getNominative().hashCode();
    hash = (37 * hash) + GENITIVE_FIELD_NUMBER;
    hash = (53 * hash) + getGenitive().hashCode();
    hash = (37 * hash) + DATIVE_FIELD_NUMBER;
    hash = (53 * hash) + getDative().hashCode();
    hash = (37 * hash) + ACCUSATIVE_FIELD_NUMBER;
    hash = (53 * hash) + getAccusative().hashCode();
    hash = (37 * hash) + INSTRUMENTAL_FIELD_NUMBER;
    hash = (53 * hash) + getInstrumental().hashCode();
    hash = (37 * hash) + PREPOSITIONAL_FIELD_NUMBER;
    hash = (53 * hash) + getPrepositional().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.lower.document.grpc.proto.CaseForms parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.lower.document.grpc.proto.CaseForms parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.lower.document.grpc.proto.CaseForms parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.lower.document.grpc.proto.CaseForms prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code namedeclension.CaseForms}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:namedeclension.CaseForms)
      org.lower.document.grpc.proto.CaseFormsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_CaseForms_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_CaseForms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lower.document.grpc.proto.CaseForms.class, org.lower.document.grpc.proto.CaseForms.Builder.class);
    }

    // Construct using org.lower.document.grpc.proto.CaseForms.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      nominative_ = "";
      genitive_ = "";
      dative_ = "";
      accusative_ = "";
      instrumental_ = "";
      prepositional_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_CaseForms_descriptor;
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.CaseForms getDefaultInstanceForType() {
      return org.lower.document.grpc.proto.CaseForms.getDefaultInstance();
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.CaseForms build() {
      org.lower.document.grpc.proto.CaseForms result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.CaseForms buildPartial() {
      org.lower.document.grpc.proto.CaseForms result = new org.lower.document.grpc.proto.CaseForms(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.lower.document.grpc.proto.CaseForms result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.nominative_ = nominative_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.genitive_ = genitive_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.dative_ = dative_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.accusative_ = accusative_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.instrumental_ = instrumental_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.prepositional_ = prepositional_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.lower.document.grpc.proto.CaseForms) {
        return mergeFrom((org.lower.document.grpc.proto.CaseForms)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.lower.document.grpc.proto.CaseForms other) {
      if (other == org.lower.document.grpc.proto.CaseForms.getDefaultInstance()) return this;
      if (!other.getNominative().isEmpty()) {
        nominative_ = other.nominative_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getGenitive().isEmpty()) {
        genitive_ = other.genitive_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getDative().isEmpty()) {
        dative_ = other.dative_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getAccusative().isEmpty()) {
        accusative_ = other.accusative_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.getInstrumental().isEmpty()) {
        instrumental_ = other.instrumental_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      if (!other.getPrepositional().isEmpty()) {
        prepositional_ = other.prepositional_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              nominative_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              genitive_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              dative_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              accusative_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              instrumental_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              prepositional_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object nominative_ = "";
    /**
     * <code>string nominative = 1;</code>
     * @return The nominative.
     */
    public java.lang.String getNominative() {
      java.lang.Object ref = nominative_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nominative_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string nominative = 1;</code>
     * @return The bytes for nominative.
     */
    public com.google.protobuf.ByteString
        getNominativeBytes() {
      java.lang.Object ref = nominative_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nominative_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string nominative = 1;</code>
     * @param value The nominative to set.
     * @return This builder for chaining.
     */
    public Builder setNominative(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      nominative_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string nominative = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearNominative() {
      nominative_ = getDefaultInstance().getNominative();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string nominative = 1;</code>
     * @param value The bytes for nominative to set.
     * @return This builder for chaining.
     */
    public Builder setNominativeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      nominative_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object genitive_ = "";
    /**
     * <code>string genitive = 2;</code>
     * @return The genitive.
     */
    public java.lang.String getGenitive() {
      java.lang.Object ref = genitive_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        genitive_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string genitive = 2;</code>
     * @return The bytes for genitive.
     */
    public com.google.protobuf.ByteString
        getGenitiveBytes() {
      java.lang.Object ref = genitive_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        genitive_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string genitive = 2;</code>
     * @param value The genitive to set.
     * @return This builder for chaining.
     */
    public Builder setGenitive(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      genitive_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string genitive = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGenitive() {
      genitive_ = getDefaultInstance().getGenitive();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string genitive = 2;</code>
     * @param value The bytes for genitive to set.
     * @return This builder for chaining.
     */
    public Builder setGenitiveBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      genitive_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object dative_ = "";
    /**
     * <code>string dative = 3;</code>
     * @return The dative.
     */
    public java.lang.String getDative() {
      java.lang.Object ref = dative_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dative_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string dative = 3;</code>
     * @return The bytes for dative.
     */
    public com.google.protobuf.ByteString
        getDativeBytes() {
      java.lang.Object ref = dative_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dative_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string dative = 3;</code>
     * @param value The dative to set.
     * @return This builder for chaining.
     */
    public Builder setDative(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      dative_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string dative = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDative() {
      dative_ = getDefaultInstance().getDative();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string dative = 3;</code>
     * @param value The bytes for dative to set.
     * @return This builder for chaining.
     */
    public Builder setDativeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      dative_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object accusative_ = "";
    /**
     * <code>string accusative = 4;</code>
     * @return The accusative.
     */
    public java.lang.String getAccusative() {
      java.lang.Object ref = accusative_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        accusative_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string accusative = 4;</code>
     * @return The bytes for accusative.
     */
    public com.google.protobuf.ByteString
        getAccusativeBytes() {
      java.lang.Object ref = accusative_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        accusative_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string accusative = 4;</code>
     * @param value The accusative to set.
     * @return This builder for chaining.
     */
    public Builder setAccusative(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      accusative_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string accusative = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccusative() {
      accusative_ = getDefaultInstance().getAccusative();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string accusative = 4;</code>
     * @param value The bytes for accusative to set.
     * @return This builder for chaining.
     */
    public Builder setAccusativeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      accusative_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object instrumental_ = "";
    /**
     * <code>string instrumental = 5;</code>
     * @return The instrumental.
     */
    public java.lang.String getInstrumental() {
      java.lang.Object ref = instrumental_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        instrumental_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string instrumental = 5;</code>
     * @return The bytes for instrumental.
     */
    public com.google.protobuf.ByteString
        getInstrumentalBytes() {
      java.lang.Object ref = instrumental_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        instrumental_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string instrumental = 5;</code>
     * @param value The instrumental to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumental(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      instrumental_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>string instrumental = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearInstrumental() {
      instrumental_ = getDefaultInstance().getInstrumental();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <code>string instrumental = 5;</code>
     * @param value The bytes for instrumental to set.
     * @return This builder for chaining.
     */
    public Builder setInstrumentalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      instrumental_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object prepositional_ = "";
    /**
     * <code>string prepositional = 6;</code>
     * @return The prepositional.
     */
    public java.lang.String getPrepositional() {
      java.lang.Object ref = prepositional_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prepositional_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prepositional = 6;</code>
     * @return The bytes for prepositional.
     */
    public com.google.protobuf.ByteString
        getPrepositionalBytes() {
      java.lang.Object ref = prepositional_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prepositional_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prepositional = 6;</code>
     * @param value The prepositional to set.
     * @return This builder for chaining.
     */
    public Builder setPrepositional(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      prepositional_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>string prepositional = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrepositional() {
      prepositional_ = getDefaultInstance().getPrepositional();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <code>string prepositional = 6;</code>
     * @param value The bytes for prepositional to set.
     * @return This builder for chaining.
     */
    public Builder setPrepositionalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      prepositional_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:namedeclension.CaseForms)
  }

  // @@protoc_insertion_point(class_scope:namedeclension.CaseForms)
  private static final org.lower.document.grpc.proto.CaseForms DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.lower.document.grpc.proto.CaseForms();
  }

  public static org.lower.document.grpc.proto.CaseForms getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CaseForms>
      PARSER = new com.google.protobuf.AbstractParser<CaseForms>() {
    @java.lang.Override
    public CaseForms parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CaseForms> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CaseForms> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.lower.document.grpc.proto.CaseForms getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

