// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

/**
 * Protobuf type {@code namedeclension.DeclinedName}
 */
public final class DeclinedName extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:namedeclension.DeclinedName)
    DeclinedNameOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeclinedName.newBuilder() to construct.
  private DeclinedName(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeclinedName() {
    confidence_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeclinedName();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclinedName_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclinedName_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.lower.document.grpc.proto.DeclinedName.class, org.lower.document.grpc.proto.DeclinedName.Builder.class);
  }

  private int bitField0_;
  public static final int CASES_FIELD_NUMBER = 1;
  private org.lower.document.grpc.proto.CaseForms cases_;
  /**
   * <code>.namedeclension.CaseForms cases = 1;</code>
   * @return Whether the cases field is set.
   */
  @java.lang.Override
  public boolean hasCases() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.namedeclension.CaseForms cases = 1;</code>
   * @return The cases.
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.CaseForms getCases() {
    return cases_ == null ? org.lower.document.grpc.proto.CaseForms.getDefaultInstance() : cases_;
  }
  /**
   * <code>.namedeclension.CaseForms cases = 1;</code>
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.CaseFormsOrBuilder getCasesOrBuilder() {
    return cases_ == null ? org.lower.document.grpc.proto.CaseForms.getDefaultInstance() : cases_;
  }

  public static final int CONFIDENCE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object confidence_ = "";
  /**
   * <code>string confidence = 2;</code>
   * @return The confidence.
   */
  @java.lang.Override
  public java.lang.String getConfidence() {
    java.lang.Object ref = confidence_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      confidence_ = s;
      return s;
    }
  }
  /**
   * <code>string confidence = 2;</code>
   * @return The bytes for confidence.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getConfidenceBytes() {
    java.lang.Object ref = confidence_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      confidence_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getCases());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(confidence_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, confidence_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getCases());
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(confidence_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, confidence_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.lower.document.grpc.proto.DeclinedName)) {
      return super.equals(obj);
    }
    org.lower.document.grpc.proto.DeclinedName other = (org.lower.document.grpc.proto.DeclinedName) obj;

    if (hasCases() != other.hasCases()) return false;
    if (hasCases()) {
      if (!getCases()
          .equals(other.getCases())) return false;
    }
    if (!getConfidence()
        .equals(other.getConfidence())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasCases()) {
      hash = (37 * hash) + CASES_FIELD_NUMBER;
      hash = (53 * hash) + getCases().hashCode();
    }
    hash = (37 * hash) + CONFIDENCE_FIELD_NUMBER;
    hash = (53 * hash) + getConfidence().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.lower.document.grpc.proto.DeclinedName parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.lower.document.grpc.proto.DeclinedName parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.lower.document.grpc.proto.DeclinedName parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.lower.document.grpc.proto.DeclinedName prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code namedeclension.DeclinedName}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:namedeclension.DeclinedName)
      org.lower.document.grpc.proto.DeclinedNameOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclinedName_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclinedName_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lower.document.grpc.proto.DeclinedName.class, org.lower.document.grpc.proto.DeclinedName.Builder.class);
    }

    // Construct using org.lower.document.grpc.proto.DeclinedName.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCasesFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cases_ = null;
      if (casesBuilder_ != null) {
        casesBuilder_.dispose();
        casesBuilder_ = null;
      }
      confidence_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclinedName_descriptor;
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.DeclinedName getDefaultInstanceForType() {
      return org.lower.document.grpc.proto.DeclinedName.getDefaultInstance();
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.DeclinedName build() {
      org.lower.document.grpc.proto.DeclinedName result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.DeclinedName buildPartial() {
      org.lower.document.grpc.proto.DeclinedName result = new org.lower.document.grpc.proto.DeclinedName(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.lower.document.grpc.proto.DeclinedName result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cases_ = casesBuilder_ == null
            ? cases_
            : casesBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.confidence_ = confidence_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.lower.document.grpc.proto.DeclinedName) {
        return mergeFrom((org.lower.document.grpc.proto.DeclinedName)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.lower.document.grpc.proto.DeclinedName other) {
      if (other == org.lower.document.grpc.proto.DeclinedName.getDefaultInstance()) return this;
      if (other.hasCases()) {
        mergeCases(other.getCases());
      }
      if (!other.getConfidence().isEmpty()) {
        confidence_ = other.confidence_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getCasesFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              confidence_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.lower.document.grpc.proto.CaseForms cases_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.CaseForms, org.lower.document.grpc.proto.CaseForms.Builder, org.lower.document.grpc.proto.CaseFormsOrBuilder> casesBuilder_;
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     * @return Whether the cases field is set.
     */
    public boolean hasCases() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     * @return The cases.
     */
    public org.lower.document.grpc.proto.CaseForms getCases() {
      if (casesBuilder_ == null) {
        return cases_ == null ? org.lower.document.grpc.proto.CaseForms.getDefaultInstance() : cases_;
      } else {
        return casesBuilder_.getMessage();
      }
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     */
    public Builder setCases(org.lower.document.grpc.proto.CaseForms value) {
      if (casesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        cases_ = value;
      } else {
        casesBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     */
    public Builder setCases(
        org.lower.document.grpc.proto.CaseForms.Builder builderForValue) {
      if (casesBuilder_ == null) {
        cases_ = builderForValue.build();
      } else {
        casesBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     */
    public Builder mergeCases(org.lower.document.grpc.proto.CaseForms value) {
      if (casesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          cases_ != null &&
          cases_ != org.lower.document.grpc.proto.CaseForms.getDefaultInstance()) {
          getCasesBuilder().mergeFrom(value);
        } else {
          cases_ = value;
        }
      } else {
        casesBuilder_.mergeFrom(value);
      }
      if (cases_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     */
    public Builder clearCases() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cases_ = null;
      if (casesBuilder_ != null) {
        casesBuilder_.dispose();
        casesBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     */
    public org.lower.document.grpc.proto.CaseForms.Builder getCasesBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getCasesFieldBuilder().getBuilder();
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     */
    public org.lower.document.grpc.proto.CaseFormsOrBuilder getCasesOrBuilder() {
      if (casesBuilder_ != null) {
        return casesBuilder_.getMessageOrBuilder();
      } else {
        return cases_ == null ?
            org.lower.document.grpc.proto.CaseForms.getDefaultInstance() : cases_;
      }
    }
    /**
     * <code>.namedeclension.CaseForms cases = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.CaseForms, org.lower.document.grpc.proto.CaseForms.Builder, org.lower.document.grpc.proto.CaseFormsOrBuilder> 
        getCasesFieldBuilder() {
      if (casesBuilder_ == null) {
        casesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.lower.document.grpc.proto.CaseForms, org.lower.document.grpc.proto.CaseForms.Builder, org.lower.document.grpc.proto.CaseFormsOrBuilder>(
                getCases(),
                getParentForChildren(),
                isClean());
        cases_ = null;
      }
      return casesBuilder_;
    }

    private java.lang.Object confidence_ = "";
    /**
     * <code>string confidence = 2;</code>
     * @return The confidence.
     */
    public java.lang.String getConfidence() {
      java.lang.Object ref = confidence_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        confidence_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string confidence = 2;</code>
     * @return The bytes for confidence.
     */
    public com.google.protobuf.ByteString
        getConfidenceBytes() {
      java.lang.Object ref = confidence_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        confidence_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string confidence = 2;</code>
     * @param value The confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidence(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      confidence_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string confidence = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearConfidence() {
      confidence_ = getDefaultInstance().getConfidence();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string confidence = 2;</code>
     * @param value The bytes for confidence to set.
     * @return This builder for chaining.
     */
    public Builder setConfidenceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      confidence_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:namedeclension.DeclinedName)
  }

  // @@protoc_insertion_point(class_scope:namedeclension.DeclinedName)
  private static final org.lower.document.grpc.proto.DeclinedName DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.lower.document.grpc.proto.DeclinedName();
  }

  public static org.lower.document.grpc.proto.DeclinedName getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeclinedName>
      PARSER = new com.google.protobuf.AbstractParser<DeclinedName>() {
    @java.lang.Override
    public DeclinedName parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeclinedName> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeclinedName> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.lower.document.grpc.proto.DeclinedName getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

