// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

public interface DeclineFullNameRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:namedeclension.DeclineFullNameRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string last_name = 1;</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <code>string last_name = 1;</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <code>string first_name = 2;</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <code>string first_name = 2;</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <code>string middle_name = 3;</code>
   * @return The middleName.
   */
  java.lang.String getMiddleName();
  /**
   * <code>string middle_name = 3;</code>
   * @return The bytes for middleName.
   */
  com.google.protobuf.ByteString
      getMiddleNameBytes();

  /**
   * <code>.namedeclension.Gender gender = 4;</code>
   * @return The enum numeric value on the wire for gender.
   */
  int getGenderValue();
  /**
   * <code>.namedeclension.Gender gender = 4;</code>
   * @return The gender.
   */
  org.lower.document.grpc.proto.Gender getGender();
}
