// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

/**
 * Protobuf type {@code namedeclension.DeclineFullNameResponse}
 */
public final class DeclineFullNameResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:namedeclension.DeclineFullNameResponse)
    DeclineFullNameResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeclineFullNameResponse.newBuilder() to construct.
  private DeclineFullNameResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeclineFullNameResponse() {
    detectedGender_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeclineFullNameResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclineFullNameResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclineFullNameResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.lower.document.grpc.proto.DeclineFullNameResponse.class, org.lower.document.grpc.proto.DeclineFullNameResponse.Builder.class);
  }

  private int bitField0_;
  public static final int LAST_NAME_FIELD_NUMBER = 1;
  private org.lower.document.grpc.proto.DeclinedName lastName_;
  /**
   * <code>.namedeclension.DeclinedName last_name = 1;</code>
   * @return Whether the lastName field is set.
   */
  @java.lang.Override
  public boolean hasLastName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.namedeclension.DeclinedName last_name = 1;</code>
   * @return The lastName.
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.DeclinedName getLastName() {
    return lastName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : lastName_;
  }
  /**
   * <code>.namedeclension.DeclinedName last_name = 1;</code>
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.DeclinedNameOrBuilder getLastNameOrBuilder() {
    return lastName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : lastName_;
  }

  public static final int FIRST_NAME_FIELD_NUMBER = 2;
  private org.lower.document.grpc.proto.DeclinedName firstName_;
  /**
   * <code>.namedeclension.DeclinedName first_name = 2;</code>
   * @return Whether the firstName field is set.
   */
  @java.lang.Override
  public boolean hasFirstName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.namedeclension.DeclinedName first_name = 2;</code>
   * @return The firstName.
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.DeclinedName getFirstName() {
    return firstName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : firstName_;
  }
  /**
   * <code>.namedeclension.DeclinedName first_name = 2;</code>
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.DeclinedNameOrBuilder getFirstNameOrBuilder() {
    return firstName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : firstName_;
  }

  public static final int MIDDLE_NAME_FIELD_NUMBER = 3;
  private org.lower.document.grpc.proto.DeclinedName middleName_;
  /**
   * <code>.namedeclension.DeclinedName middle_name = 3;</code>
   * @return Whether the middleName field is set.
   */
  @java.lang.Override
  public boolean hasMiddleName() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>.namedeclension.DeclinedName middle_name = 3;</code>
   * @return The middleName.
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.DeclinedName getMiddleName() {
    return middleName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : middleName_;
  }
  /**
   * <code>.namedeclension.DeclinedName middle_name = 3;</code>
   */
  @java.lang.Override
  public org.lower.document.grpc.proto.DeclinedNameOrBuilder getMiddleNameOrBuilder() {
    return middleName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : middleName_;
  }

  public static final int DETECTED_GENDER_FIELD_NUMBER = 4;
  private int detectedGender_ = 0;
  /**
   * <code>.namedeclension.Gender detected_gender = 4;</code>
   * @return The enum numeric value on the wire for detectedGender.
   */
  @java.lang.Override public int getDetectedGenderValue() {
    return detectedGender_;
  }
  /**
   * <code>.namedeclension.Gender detected_gender = 4;</code>
   * @return The detectedGender.
   */
  @java.lang.Override public org.lower.document.grpc.proto.Gender getDetectedGender() {
    org.lower.document.grpc.proto.Gender result = org.lower.document.grpc.proto.Gender.forNumber(detectedGender_);
    return result == null ? org.lower.document.grpc.proto.Gender.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getLastName());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(2, getFirstName());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getMiddleName());
    }
    if (detectedGender_ != org.lower.document.grpc.proto.Gender.GENDER_UNKNOWN.getNumber()) {
      output.writeEnum(4, detectedGender_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getLastName());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getFirstName());
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getMiddleName());
    }
    if (detectedGender_ != org.lower.document.grpc.proto.Gender.GENDER_UNKNOWN.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, detectedGender_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.lower.document.grpc.proto.DeclineFullNameResponse)) {
      return super.equals(obj);
    }
    org.lower.document.grpc.proto.DeclineFullNameResponse other = (org.lower.document.grpc.proto.DeclineFullNameResponse) obj;

    if (hasLastName() != other.hasLastName()) return false;
    if (hasLastName()) {
      if (!getLastName()
          .equals(other.getLastName())) return false;
    }
    if (hasFirstName() != other.hasFirstName()) return false;
    if (hasFirstName()) {
      if (!getFirstName()
          .equals(other.getFirstName())) return false;
    }
    if (hasMiddleName() != other.hasMiddleName()) return false;
    if (hasMiddleName()) {
      if (!getMiddleName()
          .equals(other.getMiddleName())) return false;
    }
    if (detectedGender_ != other.detectedGender_) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasLastName()) {
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
    }
    if (hasFirstName()) {
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
    }
    if (hasMiddleName()) {
      hash = (37 * hash) + MIDDLE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getMiddleName().hashCode();
    }
    hash = (37 * hash) + DETECTED_GENDER_FIELD_NUMBER;
    hash = (53 * hash) + detectedGender_;
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.lower.document.grpc.proto.DeclineFullNameResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.lower.document.grpc.proto.DeclineFullNameResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code namedeclension.DeclineFullNameResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:namedeclension.DeclineFullNameResponse)
      org.lower.document.grpc.proto.DeclineFullNameResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclineFullNameResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclineFullNameResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.lower.document.grpc.proto.DeclineFullNameResponse.class, org.lower.document.grpc.proto.DeclineFullNameResponse.Builder.class);
    }

    // Construct using org.lower.document.grpc.proto.DeclineFullNameResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getLastNameFieldBuilder();
        getFirstNameFieldBuilder();
        getMiddleNameFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      lastName_ = null;
      if (lastNameBuilder_ != null) {
        lastNameBuilder_.dispose();
        lastNameBuilder_ = null;
      }
      firstName_ = null;
      if (firstNameBuilder_ != null) {
        firstNameBuilder_.dispose();
        firstNameBuilder_ = null;
      }
      middleName_ = null;
      if (middleNameBuilder_ != null) {
        middleNameBuilder_.dispose();
        middleNameBuilder_ = null;
      }
      detectedGender_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.lower.document.grpc.proto.NameDeclensionProto.internal_static_namedeclension_DeclineFullNameResponse_descriptor;
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.DeclineFullNameResponse getDefaultInstanceForType() {
      return org.lower.document.grpc.proto.DeclineFullNameResponse.getDefaultInstance();
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.DeclineFullNameResponse build() {
      org.lower.document.grpc.proto.DeclineFullNameResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.lower.document.grpc.proto.DeclineFullNameResponse buildPartial() {
      org.lower.document.grpc.proto.DeclineFullNameResponse result = new org.lower.document.grpc.proto.DeclineFullNameResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(org.lower.document.grpc.proto.DeclineFullNameResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.lastName_ = lastNameBuilder_ == null
            ? lastName_
            : lastNameBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.firstName_ = firstNameBuilder_ == null
            ? firstName_
            : firstNameBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.middleName_ = middleNameBuilder_ == null
            ? middleName_
            : middleNameBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.detectedGender_ = detectedGender_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.lower.document.grpc.proto.DeclineFullNameResponse) {
        return mergeFrom((org.lower.document.grpc.proto.DeclineFullNameResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.lower.document.grpc.proto.DeclineFullNameResponse other) {
      if (other == org.lower.document.grpc.proto.DeclineFullNameResponse.getDefaultInstance()) return this;
      if (other.hasLastName()) {
        mergeLastName(other.getLastName());
      }
      if (other.hasFirstName()) {
        mergeFirstName(other.getFirstName());
      }
      if (other.hasMiddleName()) {
        mergeMiddleName(other.getMiddleName());
      }
      if (other.detectedGender_ != 0) {
        setDetectedGenderValue(other.getDetectedGenderValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getLastNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getFirstNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getMiddleNameFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              detectedGender_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private org.lower.document.grpc.proto.DeclinedName lastName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder> lastNameBuilder_;
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     * @return Whether the lastName field is set.
     */
    public boolean hasLastName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     * @return The lastName.
     */
    public org.lower.document.grpc.proto.DeclinedName getLastName() {
      if (lastNameBuilder_ == null) {
        return lastName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : lastName_;
      } else {
        return lastNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     */
    public Builder setLastName(org.lower.document.grpc.proto.DeclinedName value) {
      if (lastNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        lastName_ = value;
      } else {
        lastNameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     */
    public Builder setLastName(
        org.lower.document.grpc.proto.DeclinedName.Builder builderForValue) {
      if (lastNameBuilder_ == null) {
        lastName_ = builderForValue.build();
      } else {
        lastNameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     */
    public Builder mergeLastName(org.lower.document.grpc.proto.DeclinedName value) {
      if (lastNameBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          lastName_ != null &&
          lastName_ != org.lower.document.grpc.proto.DeclinedName.getDefaultInstance()) {
          getLastNameBuilder().mergeFrom(value);
        } else {
          lastName_ = value;
        }
      } else {
        lastNameBuilder_.mergeFrom(value);
      }
      if (lastName_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     */
    public Builder clearLastName() {
      bitField0_ = (bitField0_ & ~0x00000001);
      lastName_ = null;
      if (lastNameBuilder_ != null) {
        lastNameBuilder_.dispose();
        lastNameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     */
    public org.lower.document.grpc.proto.DeclinedName.Builder getLastNameBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getLastNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     */
    public org.lower.document.grpc.proto.DeclinedNameOrBuilder getLastNameOrBuilder() {
      if (lastNameBuilder_ != null) {
        return lastNameBuilder_.getMessageOrBuilder();
      } else {
        return lastName_ == null ?
            org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : lastName_;
      }
    }
    /**
     * <code>.namedeclension.DeclinedName last_name = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder> 
        getLastNameFieldBuilder() {
      if (lastNameBuilder_ == null) {
        lastNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder>(
                getLastName(),
                getParentForChildren(),
                isClean());
        lastName_ = null;
      }
      return lastNameBuilder_;
    }

    private org.lower.document.grpc.proto.DeclinedName firstName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder> firstNameBuilder_;
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     * @return Whether the firstName field is set.
     */
    public boolean hasFirstName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     * @return The firstName.
     */
    public org.lower.document.grpc.proto.DeclinedName getFirstName() {
      if (firstNameBuilder_ == null) {
        return firstName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : firstName_;
      } else {
        return firstNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     */
    public Builder setFirstName(org.lower.document.grpc.proto.DeclinedName value) {
      if (firstNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        firstName_ = value;
      } else {
        firstNameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     */
    public Builder setFirstName(
        org.lower.document.grpc.proto.DeclinedName.Builder builderForValue) {
      if (firstNameBuilder_ == null) {
        firstName_ = builderForValue.build();
      } else {
        firstNameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     */
    public Builder mergeFirstName(org.lower.document.grpc.proto.DeclinedName value) {
      if (firstNameBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          firstName_ != null &&
          firstName_ != org.lower.document.grpc.proto.DeclinedName.getDefaultInstance()) {
          getFirstNameBuilder().mergeFrom(value);
        } else {
          firstName_ = value;
        }
      } else {
        firstNameBuilder_.mergeFrom(value);
      }
      if (firstName_ != null) {
        bitField0_ |= 0x00000002;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     */
    public Builder clearFirstName() {
      bitField0_ = (bitField0_ & ~0x00000002);
      firstName_ = null;
      if (firstNameBuilder_ != null) {
        firstNameBuilder_.dispose();
        firstNameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     */
    public org.lower.document.grpc.proto.DeclinedName.Builder getFirstNameBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getFirstNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     */
    public org.lower.document.grpc.proto.DeclinedNameOrBuilder getFirstNameOrBuilder() {
      if (firstNameBuilder_ != null) {
        return firstNameBuilder_.getMessageOrBuilder();
      } else {
        return firstName_ == null ?
            org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : firstName_;
      }
    }
    /**
     * <code>.namedeclension.DeclinedName first_name = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder> 
        getFirstNameFieldBuilder() {
      if (firstNameBuilder_ == null) {
        firstNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder>(
                getFirstName(),
                getParentForChildren(),
                isClean());
        firstName_ = null;
      }
      return firstNameBuilder_;
    }

    private org.lower.document.grpc.proto.DeclinedName middleName_;
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder> middleNameBuilder_;
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     * @return Whether the middleName field is set.
     */
    public boolean hasMiddleName() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     * @return The middleName.
     */
    public org.lower.document.grpc.proto.DeclinedName getMiddleName() {
      if (middleNameBuilder_ == null) {
        return middleName_ == null ? org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : middleName_;
      } else {
        return middleNameBuilder_.getMessage();
      }
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     */
    public Builder setMiddleName(org.lower.document.grpc.proto.DeclinedName value) {
      if (middleNameBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        middleName_ = value;
      } else {
        middleNameBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     */
    public Builder setMiddleName(
        org.lower.document.grpc.proto.DeclinedName.Builder builderForValue) {
      if (middleNameBuilder_ == null) {
        middleName_ = builderForValue.build();
      } else {
        middleNameBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     */
    public Builder mergeMiddleName(org.lower.document.grpc.proto.DeclinedName value) {
      if (middleNameBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          middleName_ != null &&
          middleName_ != org.lower.document.grpc.proto.DeclinedName.getDefaultInstance()) {
          getMiddleNameBuilder().mergeFrom(value);
        } else {
          middleName_ = value;
        }
      } else {
        middleNameBuilder_.mergeFrom(value);
      }
      if (middleName_ != null) {
        bitField0_ |= 0x00000004;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     */
    public Builder clearMiddleName() {
      bitField0_ = (bitField0_ & ~0x00000004);
      middleName_ = null;
      if (middleNameBuilder_ != null) {
        middleNameBuilder_.dispose();
        middleNameBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     */
    public org.lower.document.grpc.proto.DeclinedName.Builder getMiddleNameBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getMiddleNameFieldBuilder().getBuilder();
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     */
    public org.lower.document.grpc.proto.DeclinedNameOrBuilder getMiddleNameOrBuilder() {
      if (middleNameBuilder_ != null) {
        return middleNameBuilder_.getMessageOrBuilder();
      } else {
        return middleName_ == null ?
            org.lower.document.grpc.proto.DeclinedName.getDefaultInstance() : middleName_;
      }
    }
    /**
     * <code>.namedeclension.DeclinedName middle_name = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder> 
        getMiddleNameFieldBuilder() {
      if (middleNameBuilder_ == null) {
        middleNameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            org.lower.document.grpc.proto.DeclinedName, org.lower.document.grpc.proto.DeclinedName.Builder, org.lower.document.grpc.proto.DeclinedNameOrBuilder>(
                getMiddleName(),
                getParentForChildren(),
                isClean());
        middleName_ = null;
      }
      return middleNameBuilder_;
    }

    private int detectedGender_ = 0;
    /**
     * <code>.namedeclension.Gender detected_gender = 4;</code>
     * @return The enum numeric value on the wire for detectedGender.
     */
    @java.lang.Override public int getDetectedGenderValue() {
      return detectedGender_;
    }
    /**
     * <code>.namedeclension.Gender detected_gender = 4;</code>
     * @param value The enum numeric value on the wire for detectedGender to set.
     * @return This builder for chaining.
     */
    public Builder setDetectedGenderValue(int value) {
      detectedGender_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.Gender detected_gender = 4;</code>
     * @return The detectedGender.
     */
    @java.lang.Override
    public org.lower.document.grpc.proto.Gender getDetectedGender() {
      org.lower.document.grpc.proto.Gender result = org.lower.document.grpc.proto.Gender.forNumber(detectedGender_);
      return result == null ? org.lower.document.grpc.proto.Gender.UNRECOGNIZED : result;
    }
    /**
     * <code>.namedeclension.Gender detected_gender = 4;</code>
     * @param value The detectedGender to set.
     * @return This builder for chaining.
     */
    public Builder setDetectedGender(org.lower.document.grpc.proto.Gender value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      detectedGender_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.namedeclension.Gender detected_gender = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearDetectedGender() {
      bitField0_ = (bitField0_ & ~0x00000008);
      detectedGender_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:namedeclension.DeclineFullNameResponse)
  }

  // @@protoc_insertion_point(class_scope:namedeclension.DeclineFullNameResponse)
  private static final org.lower.document.grpc.proto.DeclineFullNameResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.lower.document.grpc.proto.DeclineFullNameResponse();
  }

  public static org.lower.document.grpc.proto.DeclineFullNameResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeclineFullNameResponse>
      PARSER = new com.google.protobuf.AbstractParser<DeclineFullNameResponse>() {
    @java.lang.Override
    public DeclineFullNameResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<DeclineFullNameResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeclineFullNameResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.lower.document.grpc.proto.DeclineFullNameResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

