// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

public interface DeclinedNameOrBuilder extends
    // @@protoc_insertion_point(interface_extends:namedeclension.DeclinedName)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.namedeclension.CaseForms cases = 1;</code>
   * @return Whether the cases field is set.
   */
  boolean hasCases();
  /**
   * <code>.namedeclension.CaseForms cases = 1;</code>
   * @return The cases.
   */
  org.lower.document.grpc.proto.CaseForms getCases();
  /**
   * <code>.namedeclension.CaseForms cases = 1;</code>
   */
  org.lower.document.grpc.proto.CaseFormsOrBuilder getCasesOrBuilder();

  /**
   * <code>string confidence = 2;</code>
   * @return The confidence.
   */
  java.lang.String getConfidence();
  /**
   * <code>string confidence = 2;</code>
   * @return The bytes for confidence.
   */
  com.google.protobuf.ByteString
      getConfidenceBytes();
}
