// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

public interface DeclineFullNameResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:namedeclension.DeclineFullNameResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.namedeclension.DeclinedName last_name = 1;</code>
   * @return Whether the lastName field is set.
   */
  boolean hasLastName();
  /**
   * <code>.namedeclension.DeclinedName last_name = 1;</code>
   * @return The lastName.
   */
  org.lower.document.grpc.proto.DeclinedName getLastName();
  /**
   * <code>.namedeclension.DeclinedName last_name = 1;</code>
   */
  org.lower.document.grpc.proto.DeclinedNameOrBuilder getLastNameOrBuilder();

  /**
   * <code>.namedeclension.DeclinedName first_name = 2;</code>
   * @return Whether the firstName field is set.
   */
  boolean hasFirstName();
  /**
   * <code>.namedeclension.DeclinedName first_name = 2;</code>
   * @return The firstName.
   */
  org.lower.document.grpc.proto.DeclinedName getFirstName();
  /**
   * <code>.namedeclension.DeclinedName first_name = 2;</code>
   */
  org.lower.document.grpc.proto.DeclinedNameOrBuilder getFirstNameOrBuilder();

  /**
   * <code>.namedeclension.DeclinedName middle_name = 3;</code>
   * @return Whether the middleName field is set.
   */
  boolean hasMiddleName();
  /**
   * <code>.namedeclension.DeclinedName middle_name = 3;</code>
   * @return The middleName.
   */
  org.lower.document.grpc.proto.DeclinedName getMiddleName();
  /**
   * <code>.namedeclension.DeclinedName middle_name = 3;</code>
   */
  org.lower.document.grpc.proto.DeclinedNameOrBuilder getMiddleNameOrBuilder();

  /**
   * <code>.namedeclension.Gender detected_gender = 4;</code>
   * @return The enum numeric value on the wire for detectedGender.
   */
  int getDetectedGenderValue();
  /**
   * <code>.namedeclension.Gender detected_gender = 4;</code>
   * @return The detectedGender.
   */
  org.lower.document.grpc.proto.Gender getDetectedGender();
}
