// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ame_declension.proto

// Protobuf Java Version: 3.25.3
package org.lower.document.grpc.proto;

public final class NameDeclensionProto {
  private NameDeclensionProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_namedeclension_DeclineFullNameRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_namedeclension_DeclineFullNameRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_namedeclension_CaseForms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_namedeclension_CaseForms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_namedeclension_DeclinedName_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_namedeclension_DeclinedName_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_namedeclension_DeclineFullNameResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_namedeclension_DeclineFullNameResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ame_declension.proto\022\016namedeclension\"|" +
      "\n\026DeclineFullNameRequest\022\021\n\tlast_name\030\001 " +
      "\001(\t\022\022\n\nfirst_name\030\002 \001(\t\022\023\n\013middle_name\030\003" +
      " \001(\t\022&\n\006gender\030\004 \001(\0162\026.namedeclension.Ge" +
      "nder\"\202\001\n\tCaseForms\022\022\n\nnominative\030\001 \001(\t\022\020" +
      "\n\010genitive\030\002 \001(\t\022\016\n\006dative\030\003 \001(\t\022\022\n\naccu" +
      "sative\030\004 \001(\t\022\024\n\014instrumental\030\005 \001(\t\022\025\n\rpr" +
      "epositional\030\006 \001(\t\"L\n\014DeclinedName\022(\n\005cas" +
      "es\030\001 \001(\0132\031.namedeclension.CaseForms\022\022\n\nc" +
      "onfidence\030\002 \001(\t\"\340\001\n\027DeclineFullNameRespo" +
      "nse\022/\n\tlast_name\030\001 \001(\0132\034.namedeclension." +
      "DeclinedName\0220\n\nfirst_name\030\002 \001(\0132\034.named" +
      "eclension.DeclinedName\0221\n\013middle_name\030\003 " +
      "\001(\0132\034.namedeclension.DeclinedName\022/\n\017det" +
      "ected_gender\030\004 \001(\0162\026.namedeclension.Gend" +
      "er*@\n\006Gender\022\022\n\016GENDER_UNKNOWN\020\000\022\017\n\013GEND" +
      "ER_MALE\020\001\022\021\n\rGENDER_FEMALE\020\0022{\n\025NameDecl" +
      "ensionService\022b\n\017DeclineFullName\022&.named" +
      "eclension.DeclineFullNameRequest\032\'.named" +
      "eclension.DeclineFullNameResponseB6\n\035org" +
      ".lower.document.grpc.protoB\023NameDeclensi" +
      "onProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_namedeclension_DeclineFullNameRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_namedeclension_DeclineFullNameRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_namedeclension_DeclineFullNameRequest_descriptor,
        new java.lang.String[] { "LastName", "FirstName", "MiddleName", "Gender", });
    internal_static_namedeclension_CaseForms_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_namedeclension_CaseForms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_namedeclension_CaseForms_descriptor,
        new java.lang.String[] { "Nominative", "Genitive", "Dative", "Accusative", "Instrumental", "Prepositional", });
    internal_static_namedeclension_DeclinedName_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_namedeclension_DeclinedName_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_namedeclension_DeclinedName_descriptor,
        new java.lang.String[] { "Cases", "Confidence", });
    internal_static_namedeclension_DeclineFullNameResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_namedeclension_DeclineFullNameResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_namedeclension_DeclineFullNameResponse_descriptor,
        new java.lang.String[] { "LastName", "FirstName", "MiddleName", "DetectedGender", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
