/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables;


import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lower.document.jooq.codegen.Keys;
import org.lower.document.jooq.codegen.Public;
import org.lower.document.jooq.codegen.tables.Documents.DocumentsPath;
import org.lower.document.jooq.codegen.tables.Owners.OwnersPath;
import org.lower.document.jooq.codegen.tables.records.ClientsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Clients extends TableImpl<ClientsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.clients</code>
     */
    public static final Clients CLIENTS = new Clients();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClientsRecord> getRecordType() {
        return ClientsRecord.class;
    }

    /**
     * The column <code>public.clients.id</code>.
     */
    public final TableField<ClientsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.clients.full_name</code>.
     */
    public final TableField<ClientsRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.clients.birth_date</code>.
     */
    public final TableField<ClientsRecord, LocalDate> BIRTH_DATE = createField(DSL.name("birth_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.clients.birth_place</code>.
     */
    public final TableField<ClientsRecord, String> BIRTH_PLACE = createField(DSL.name("birth_place"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.clients.inn</code>.
     */
    public final TableField<ClientsRecord, String> INN = createField(DSL.name("inn"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>public.clients.snils</code>.
     */
    public final TableField<ClientsRecord, String> SNILS = createField(DSL.name("snils"), SQLDataType.VARCHAR(14), this, "");

    /**
     * The column <code>public.clients.address</code>.
     */
    public final TableField<ClientsRecord, String> ADDRESS = createField(DSL.name("address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.clients.created_at</code>.
     */
    public final TableField<ClientsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.clients.updated_at</code>.
     */
    public final TableField<ClientsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.clients.court_name</code>.
     */
    public final TableField<ClientsRecord, String> COURT_NAME = createField(DSL.name("court_name"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.clients.case_number</code>.
     */
    public final TableField<ClientsRecord, String> CASE_NUMBER = createField(DSL.name("case_number"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.clients.court_decision_date</code>.
     */
    public final TableField<ClientsRecord, LocalDate> COURT_DECISION_DATE = createField(DSL.name("court_decision_date"), SQLDataType.LOCALDATE, this, "");

    /**
     * The column <code>public.clients.procedure_type</code>.
     */
    public final TableField<ClientsRecord, String> PROCEDURE_TYPE = createField(DSL.name("procedure_type"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.clients.owner_id</code>.
     */
    public final TableField<ClientsRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.clients.full_name_short</code>.
     */
    public final TableField<ClientsRecord, String> FULL_NAME_SHORT = createField(DSL.name("full_name_short"), SQLDataType.VARCHAR(256), this, "");

    private Clients(Name alias, Table<ClientsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Clients(Name alias, Table<ClientsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.clients</code> table reference
     */
    public Clients(String alias) {
        this(DSL.name(alias), CLIENTS);
    }

    /**
     * Create an aliased <code>public.clients</code> table reference
     */
    public Clients(Name alias) {
        this(alias, CLIENTS);
    }

    /**
     * Create a <code>public.clients</code> table reference
     */
    public Clients() {
        this(DSL.name("clients"), null);
    }

    public <O extends Record> Clients(Table<O> path, ForeignKey<O, ClientsRecord> childPath, InverseForeignKey<O, ClientsRecord> parentPath) {
        super(path, childPath, parentPath, CLIENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ClientsPath extends Clients implements Path<ClientsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> ClientsPath(Table<O> path, ForeignKey<O, ClientsRecord> childPath, InverseForeignKey<O, ClientsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private ClientsPath(Name alias, Table<ClientsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ClientsPath as(String alias) {
            return new ClientsPath(DSL.name(alias), this);
        }

        @Override
        public ClientsPath as(Name alias) {
            return new ClientsPath(alias, this);
        }

        @Override
        public ClientsPath as(Table<?> alias) {
            return new ClientsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<ClientsRecord> getPrimaryKey() {
        return Keys.CLIENTS_PKEY;
    }

    @Override
    public List<UniqueKey<ClientsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UNIQUE_CLIENTS_INN);
    }

    @Override
    public List<ForeignKey<ClientsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CLIENTS__CLIENTS_OWNER_ID_FKEY);
    }

    private transient OwnersPath _owners;

    /**
     * Get the implicit join path to the <code>public.owners</code> table.
     */
    public OwnersPath owners() {
        if (_owners == null)
            _owners = new OwnersPath(this, Keys.CLIENTS__CLIENTS_OWNER_ID_FKEY, null);

        return _owners;
    }

    private transient DocumentsPath _documents;

    /**
     * Get the implicit to-many join path to the <code>public.documents</code>
     * table
     */
    public DocumentsPath documents() {
        if (_documents == null)
            _documents = new DocumentsPath(this, null, Keys.DOCUMENTS__DOCUMENTS_CLIENT_ID_FKEY.getInverseKey());

        return _documents;
    }

    @Override
    public Clients as(String alias) {
        return new Clients(DSL.name(alias), this);
    }

    @Override
    public Clients as(Name alias) {
        return new Clients(alias, this);
    }

    @Override
    public Clients as(Table<?> alias) {
        return new Clients(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Clients rename(String name) {
        return new Clients(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clients rename(Name name) {
        return new Clients(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Clients rename(Table<?> name) {
        return new Clients(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Condition condition) {
        return new Clients(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Clients where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Clients whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
