/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lower.document.jooq.codegen.Indexes;
import org.lower.document.jooq.codegen.Keys;
import org.lower.document.jooq.codegen.Public;
import org.lower.document.jooq.codegen.tables.records.CourtOrgsRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CourtOrgs extends TableImpl<CourtOrgsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.court_orgs</code>
     */
    public static final CourtOrgs COURT_ORGS = new CourtOrgs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CourtOrgsRecord> getRecordType() {
        return CourtOrgsRecord.class;
    }

    /**
     * The column <code>public.court_orgs.id</code>.
     */
    public final TableField<CourtOrgsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.court_orgs.doc_type</code>.
     */
    public final TableField<CourtOrgsRecord, String> DOC_TYPE = createField(DSL.name("doc_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.court_orgs.region_code</code>.
     */
    public final TableField<CourtOrgsRecord, String> REGION_CODE = createField(DSL.name("region_code"), SQLDataType.VARCHAR(10), this, "");

    /**
     * The column <code>public.court_orgs.org_name</code>.
     */
    public final TableField<CourtOrgsRecord, String> ORG_NAME = createField(DSL.name("org_name"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.court_orgs.org_address</code>.
     */
    public final TableField<CourtOrgsRecord, String> ORG_ADDRESS = createField(DSL.name("org_address"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.court_orgs.org_note</code>.
     */
    public final TableField<CourtOrgsRecord, String> ORG_NOTE = createField(DSL.name("org_note"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.court_orgs.is_active</code>.
     */
    public final TableField<CourtOrgsRecord, Boolean> IS_ACTIVE = createField(DSL.name("is_active"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.court_orgs.created_at</code>.
     */
    public final TableField<CourtOrgsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.court_orgs.updated_at</code>.
     */
    public final TableField<CourtOrgsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private CourtOrgs(Name alias, Table<CourtOrgsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CourtOrgs(Name alias, Table<CourtOrgsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.court_orgs</code> table reference
     */
    public CourtOrgs(String alias) {
        this(DSL.name(alias), COURT_ORGS);
    }

    /**
     * Create an aliased <code>public.court_orgs</code> table reference
     */
    public CourtOrgs(Name alias) {
        this(alias, COURT_ORGS);
    }

    /**
     * Create a <code>public.court_orgs</code> table reference
     */
    public CourtOrgs() {
        this(DSL.name("court_orgs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_COURT_ORGS_TYPE_ACTIVE, Indexes.IDX_COURT_ORGS_TYPE_REGION);
    }

    @Override
    public UniqueKey<CourtOrgsRecord> getPrimaryKey() {
        return Keys.COURT_ORGS_PKEY;
    }

    @Override
    public List<UniqueKey<CourtOrgsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.COURT_ORGS_DOC_TYPE_REGION_CODE_KEY);
    }

    @Override
    public CourtOrgs as(String alias) {
        return new CourtOrgs(DSL.name(alias), this);
    }

    @Override
    public CourtOrgs as(Name alias) {
        return new CourtOrgs(alias, this);
    }

    @Override
    public CourtOrgs as(Table<?> alias) {
        return new CourtOrgs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CourtOrgs rename(String name) {
        return new CourtOrgs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CourtOrgs rename(Name name) {
        return new CourtOrgs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CourtOrgs rename(Table<?> name) {
        return new CourtOrgs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtOrgs where(Condition condition) {
        return new CourtOrgs(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtOrgs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtOrgs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtOrgs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtOrgs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtOrgs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtOrgs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtOrgs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtOrgs whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtOrgs whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
