/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lower.document.jooq.codegen.Indexes;
import org.lower.document.jooq.codegen.Keys;
import org.lower.document.jooq.codegen.Public;
import org.lower.document.jooq.codegen.tables.records.CourtDecisionsRecord;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * Таблица судебных решений по делам о банкротстве
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CourtDecisions extends TableImpl<CourtDecisionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.court_decisions</code>
     */
    public static final CourtDecisions COURT_DECISIONS = new CourtDecisions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CourtDecisionsRecord> getRecordType() {
        return CourtDecisionsRecord.class;
    }

    /**
     * The column <code>public.court_decisions.id</code>. Уникальный
     * идентификатор записи
     */
    public final TableField<CourtDecisionsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid_v7()"), SQLDataType.UUID)), this, "Уникальный идентификатор записи");

    /**
     * The column <code>public.court_decisions.owner_id</code>. ID финансового
     * управляющего (владельца дела)
     */
    public final TableField<CourtDecisionsRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "ID финансового управляющего (владельца дела)");

    /**
     * The column <code>public.court_decisions.client_id</code>. ID клиента
     * (должника)
     */
    public final TableField<CourtDecisionsRecord, UUID> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.UUID.nullable(false), this, "ID клиента (должника)");

    /**
     * The column <code>public.court_decisions.court_name</code>. Наименование
     * суда в родительном падеже (например: "Арбитражного суда Ростовской
     * области")
     */
    public final TableField<CourtDecisionsRecord, String> COURT_NAME = createField(DSL.name("court_name"), SQLDataType.VARCHAR(255).nullable(false), this, "Наименование суда в родительном падеже (например: \"Арбитражного суда Ростовской области\")");

    /**
     * The column <code>public.court_decisions.decision_date</code>. Дата
     * вынесения решения о признании банкротом
     */
    public final TableField<CourtDecisionsRecord, LocalDate> DECISION_DATE = createField(DSL.name("decision_date"), SQLDataType.LOCALDATE.nullable(false), this, "Дата вынесения решения о признании банкротом");

    /**
     * The column <code>public.court_decisions.case_number</code>. Номер дела о
     * банкротстве (например: "А53-10291/2023")
     */
    public final TableField<CourtDecisionsRecord, String> CASE_NUMBER = createField(DSL.name("case_number"), SQLDataType.VARCHAR(100).nullable(false), this, "Номер дела о банкротстве (например: \"А53-10291/2023\")");

    /**
     * The column <code>public.court_decisions.created_at</code>. Дата и время
     * создания записи
     */
    public final TableField<CourtDecisionsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "Дата и время создания записи");

    /**
     * The column <code>public.court_decisions.updated_at</code>. Дата и время
     * последнего обновления записи
     */
    public final TableField<CourtDecisionsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "Дата и время последнего обновления записи");

    private CourtDecisions(Name alias, Table<CourtDecisionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private CourtDecisions(Name alias, Table<CourtDecisionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Таблица судебных решений по делам о банкротстве"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.court_decisions</code> table reference
     */
    public CourtDecisions(String alias) {
        this(DSL.name(alias), COURT_DECISIONS);
    }

    /**
     * Create an aliased <code>public.court_decisions</code> table reference
     */
    public CourtDecisions(Name alias) {
        this(alias, COURT_DECISIONS);
    }

    /**
     * Create a <code>public.court_decisions</code> table reference
     */
    public CourtDecisions() {
        this(DSL.name("court_decisions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_COURT_DECISIONS_CLIENT_CASE_NUMBER);
    }

    @Override
    public UniqueKey<CourtDecisionsRecord> getPrimaryKey() {
        return Keys.COURT_DECISIONS_PKEY;
    }

    @Override
    public CourtDecisions as(String alias) {
        return new CourtDecisions(DSL.name(alias), this);
    }

    @Override
    public CourtDecisions as(Name alias) {
        return new CourtDecisions(alias, this);
    }

    @Override
    public CourtDecisions as(Table<?> alias) {
        return new CourtDecisions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public CourtDecisions rename(String name) {
        return new CourtDecisions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CourtDecisions rename(Name name) {
        return new CourtDecisions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public CourtDecisions rename(Table<?> name) {
        return new CourtDecisions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtDecisions where(Condition condition) {
        return new CourtDecisions(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtDecisions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtDecisions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtDecisions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtDecisions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtDecisions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtDecisions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public CourtDecisions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtDecisions whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public CourtDecisions whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
