/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lower.document.jooq.codegen.Keys;
import org.lower.document.jooq.codegen.Public;
import org.lower.document.jooq.codegen.tables.Clients.ClientsPath;
import org.lower.document.jooq.codegen.tables.Users.UsersPath;
import org.lower.document.jooq.codegen.tables.records.DocumentsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Documents extends TableImpl<DocumentsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.documents</code>
     */
    public static final Documents DOCUMENTS = new Documents();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DocumentsRecord> getRecordType() {
        return DocumentsRecord.class;
    }

    /**
     * The column <code>public.documents.id</code>.
     */
    public final TableField<DocumentsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.documents.user_id</code>.
     */
    public final TableField<DocumentsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.documents.client_id</code>.
     */
    public final TableField<DocumentsRecord, UUID> CLIENT_ID = createField(DSL.name("client_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.documents.template_type</code>.
     */
    public final TableField<DocumentsRecord, String> TEMPLATE_TYPE = createField(DSL.name("template_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.documents.metadata</code>.
     */
    public final TableField<DocumentsRecord, JSONB> METADATA = createField(DSL.name("metadata"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.documents.content</code>.
     */
    public final TableField<DocumentsRecord, byte[]> CONTENT = createField(DSL.name("content"), SQLDataType.BLOB.nullable(false), this, "");

    /**
     * The column <code>public.documents.size_kb</code>.
     */
    public final TableField<DocumentsRecord, Integer> SIZE_KB = createField(DSL.name("size_kb"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.documents.created_at</code>.
     */
    public final TableField<DocumentsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.documents.updated_at</code>.
     */
    public final TableField<DocumentsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Documents(Name alias, Table<DocumentsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Documents(Name alias, Table<DocumentsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.documents</code> table reference
     */
    public Documents(String alias) {
        this(DSL.name(alias), DOCUMENTS);
    }

    /**
     * Create an aliased <code>public.documents</code> table reference
     */
    public Documents(Name alias) {
        this(alias, DOCUMENTS);
    }

    /**
     * Create a <code>public.documents</code> table reference
     */
    public Documents() {
        this(DSL.name("documents"), null);
    }

    public <O extends Record> Documents(Table<O> path, ForeignKey<O, DocumentsRecord> childPath, InverseForeignKey<O, DocumentsRecord> parentPath) {
        super(path, childPath, parentPath, DOCUMENTS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DocumentsPath extends Documents implements Path<DocumentsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DocumentsPath(Table<O> path, ForeignKey<O, DocumentsRecord> childPath, InverseForeignKey<O, DocumentsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DocumentsPath(Name alias, Table<DocumentsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DocumentsPath as(String alias) {
            return new DocumentsPath(DSL.name(alias), this);
        }

        @Override
        public DocumentsPath as(Name alias) {
            return new DocumentsPath(alias, this);
        }

        @Override
        public DocumentsPath as(Table<?> alias) {
            return new DocumentsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DocumentsRecord> getPrimaryKey() {
        return Keys.DOCUMENTS_PKEY;
    }

    @Override
    public List<ForeignKey<DocumentsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DOCUMENTS__DOCUMENTS_CLIENT_ID_FKEY, Keys.DOCUMENTS__DOCUMENTS_USER_ID_FKEY);
    }

    private transient ClientsPath _clients;

    /**
     * Get the implicit join path to the <code>public.clients</code> table.
     */
    public ClientsPath clients() {
        if (_clients == null)
            _clients = new ClientsPath(this, Keys.DOCUMENTS__DOCUMENTS_CLIENT_ID_FKEY, null);

        return _clients;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.DOCUMENTS__DOCUMENTS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public Documents as(String alias) {
        return new Documents(DSL.name(alias), this);
    }

    @Override
    public Documents as(Name alias) {
        return new Documents(alias, this);
    }

    @Override
    public Documents as(Table<?> alias) {
        return new Documents(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Documents rename(String name) {
        return new Documents(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Documents rename(Name name) {
        return new Documents(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Documents rename(Table<?> name) {
        return new Documents(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Condition condition) {
        return new Documents(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Documents where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Documents whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
