/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lower.document.jooq.codegen.Keys;
import org.lower.document.jooq.codegen.Public;
import org.lower.document.jooq.codegen.tables.Clients.ClientsPath;
import org.lower.document.jooq.codegen.tables.Staffs.StaffsPath;
import org.lower.document.jooq.codegen.tables.Users.UsersPath;
import org.lower.document.jooq.codegen.tables.records.OwnersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Owners extends TableImpl<OwnersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.owners</code>
     */
    public static final Owners OWNERS = new Owners();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OwnersRecord> getRecordType() {
        return OwnersRecord.class;
    }

    /**
     * The column <code>public.owners.id</code>.
     */
    public final TableField<OwnersRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.owners.user_id</code>.
     */
    public final TableField<OwnersRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.owners.full_name</code>.
     */
    public final TableField<OwnersRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.owners.full_name_short</code>.
     */
    public final TableField<OwnersRecord, String> FULL_NAME_SHORT = createField(DSL.name("full_name_short"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.owners.mail_address</code>.
     */
    public final TableField<OwnersRecord, String> MAIL_ADDRESS = createField(DSL.name("mail_address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.owners.email</code>.
     */
    public final TableField<OwnersRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.owners.sro_name</code>.
     */
    public final TableField<OwnersRecord, String> SRO_NAME = createField(DSL.name("sro_name"), SQLDataType.VARCHAR(500), this, "");

    /**
     * The column <code>public.owners.sro_inn</code>.
     */
    public final TableField<OwnersRecord, String> SRO_INN = createField(DSL.name("sro_inn"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>public.owners.sro_ogrn</code>.
     */
    public final TableField<OwnersRecord, String> SRO_OGRN = createField(DSL.name("sro_ogrn"), SQLDataType.VARCHAR(15), this, "");

    /**
     * The column <code>public.owners.sro_address</code>.
     */
    public final TableField<OwnersRecord, String> SRO_ADDRESS = createField(DSL.name("sro_address"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>public.owners.user_inn</code>.
     */
    public final TableField<OwnersRecord, String> USER_INN = createField(DSL.name("user_inn"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>public.owners.user_snils</code>.
     */
    public final TableField<OwnersRecord, String> USER_SNILS = createField(DSL.name("user_snils"), SQLDataType.VARCHAR(14), this, "");

    /**
     * The column <code>public.owners.created_at</code>.
     */
    public final TableField<OwnersRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.owners.updated_at</code>.
     */
    public final TableField<OwnersRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Owners(Name alias, Table<OwnersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Owners(Name alias, Table<OwnersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.owners</code> table reference
     */
    public Owners(String alias) {
        this(DSL.name(alias), OWNERS);
    }

    /**
     * Create an aliased <code>public.owners</code> table reference
     */
    public Owners(Name alias) {
        this(alias, OWNERS);
    }

    /**
     * Create a <code>public.owners</code> table reference
     */
    public Owners() {
        this(DSL.name("owners"), null);
    }

    public <O extends Record> Owners(Table<O> path, ForeignKey<O, OwnersRecord> childPath, InverseForeignKey<O, OwnersRecord> parentPath) {
        super(path, childPath, parentPath, OWNERS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class OwnersPath extends Owners implements Path<OwnersRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> OwnersPath(Table<O> path, ForeignKey<O, OwnersRecord> childPath, InverseForeignKey<O, OwnersRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private OwnersPath(Name alias, Table<OwnersRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public OwnersPath as(String alias) {
            return new OwnersPath(DSL.name(alias), this);
        }

        @Override
        public OwnersPath as(Name alias) {
            return new OwnersPath(alias, this);
        }

        @Override
        public OwnersPath as(Table<?> alias) {
            return new OwnersPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OwnersRecord> getPrimaryKey() {
        return Keys.OWNERS_PKEY;
    }

    @Override
    public List<ForeignKey<OwnersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.OWNERS__OWNERS_USER_ID_FKEY);
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.OWNERS__OWNERS_USER_ID_FKEY, null);

        return _users;
    }

    private transient ClientsPath _clients;

    /**
     * Get the implicit to-many join path to the <code>public.clients</code>
     * table
     */
    public ClientsPath clients() {
        if (_clients == null)
            _clients = new ClientsPath(this, null, Keys.CLIENTS__CLIENTS_OWNER_ID_FKEY.getInverseKey());

        return _clients;
    }

    private transient StaffsPath _staffs;

    /**
     * Get the implicit to-many join path to the <code>public.staffs</code>
     * table
     */
    public StaffsPath staffs() {
        if (_staffs == null)
            _staffs = new StaffsPath(this, null, Keys.STAFFS__STAFFS_OWNER_ID_FKEY.getInverseKey());

        return _staffs;
    }

    @Override
    public Owners as(String alias) {
        return new Owners(DSL.name(alias), this);
    }

    @Override
    public Owners as(Name alias) {
        return new Owners(alias, this);
    }

    @Override
    public Owners as(Table<?> alias) {
        return new Owners(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Owners rename(String name) {
        return new Owners(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Owners rename(Name name) {
        return new Owners(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Owners rename(Table<?> name) {
        return new Owners(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owners where(Condition condition) {
        return new Owners(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owners where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owners where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owners where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owners where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owners where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owners where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Owners where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owners whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Owners whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
