/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables;


import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lower.document.jooq.codegen.Keys;
import org.lower.document.jooq.codegen.Public;
import org.lower.document.jooq.codegen.tables.records.RecipientOrgsRecord;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RecipientOrgs extends TableImpl<RecipientOrgsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.recipient_orgs</code>
     */
    public static final RecipientOrgs RECIPIENT_ORGS = new RecipientOrgs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RecipientOrgsRecord> getRecordType() {
        return RecipientOrgsRecord.class;
    }

    /**
     * The column <code>public.recipient_orgs.id</code>.
     */
    public final TableField<RecipientOrgsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.recipient_orgs.doc_type</code>.
     */
    public final TableField<RecipientOrgsRecord, String> DOC_TYPE = createField(DSL.name("doc_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.recipient_orgs.org_name</code>.
     */
    public final TableField<RecipientOrgsRecord, String> ORG_NAME = createField(DSL.name("org_name"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.recipient_orgs.org_address</code>.
     */
    public final TableField<RecipientOrgsRecord, String> ORG_ADDRESS = createField(DSL.name("org_address"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>public.recipient_orgs.org_note</code>.
     */
    public final TableField<RecipientOrgsRecord, String> ORG_NOTE = createField(DSL.name("org_note"), SQLDataType.CLOB, this, "");

    private RecipientOrgs(Name alias, Table<RecipientOrgsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RecipientOrgs(Name alias, Table<RecipientOrgsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.recipient_orgs</code> table reference
     */
    public RecipientOrgs(String alias) {
        this(DSL.name(alias), RECIPIENT_ORGS);
    }

    /**
     * Create an aliased <code>public.recipient_orgs</code> table reference
     */
    public RecipientOrgs(Name alias) {
        this(alias, RECIPIENT_ORGS);
    }

    /**
     * Create a <code>public.recipient_orgs</code> table reference
     */
    public RecipientOrgs() {
        this(DSL.name("recipient_orgs"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RecipientOrgsRecord> getPrimaryKey() {
        return Keys.RECIPIENT_ORGS_PKEY;
    }

    @Override
    public List<UniqueKey<RecipientOrgsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.RECIPIENT_ORGS_DOC_TYPE_KEY);
    }

    @Override
    public RecipientOrgs as(String alias) {
        return new RecipientOrgs(DSL.name(alias), this);
    }

    @Override
    public RecipientOrgs as(Name alias) {
        return new RecipientOrgs(alias, this);
    }

    @Override
    public RecipientOrgs as(Table<?> alias) {
        return new RecipientOrgs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientOrgs rename(String name) {
        return new RecipientOrgs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientOrgs rename(Name name) {
        return new RecipientOrgs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RecipientOrgs rename(Table<?> name) {
        return new RecipientOrgs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientOrgs where(Condition condition) {
        return new RecipientOrgs(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientOrgs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientOrgs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientOrgs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientOrgs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientOrgs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientOrgs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RecipientOrgs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientOrgs whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RecipientOrgs whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
