/*
 * This file is generated by jOOQ.
 */
package org.lower.document.jooq.codegen.tables;


import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableLike;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.lower.document.jooq.codegen.Keys;
import org.lower.document.jooq.codegen.Public;
import org.lower.document.jooq.codegen.tables.Owners.OwnersPath;
import org.lower.document.jooq.codegen.tables.Users.UsersPath;
import org.lower.document.jooq.codegen.tables.records.StaffsRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Staffs extends TableImpl<StaffsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.staffs</code>
     */
    public static final Staffs STAFFS = new Staffs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StaffsRecord> getRecordType() {
        return StaffsRecord.class;
    }

    /**
     * The column <code>public.staffs.id</code>.
     */
    public final TableField<StaffsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false).defaultValue(DSL.field(DSL.raw("gen_random_uuid_v7()"), SQLDataType.UUID)), this, "");

    /**
     * The column <code>public.staffs.user_id</code>.
     */
    public final TableField<StaffsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.staffs.full_name</code>.
     */
    public final TableField<StaffsRecord, String> FULL_NAME = createField(DSL.name("full_name"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column <code>public.staffs.full_name_short</code>.
     */
    public final TableField<StaffsRecord, String> FULL_NAME_SHORT = createField(DSL.name("full_name_short"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.staffs.email</code>.
     */
    public final TableField<StaffsRecord, String> EMAIL = createField(DSL.name("email"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.staffs.user_inn</code>.
     */
    public final TableField<StaffsRecord, String> USER_INN = createField(DSL.name("user_inn"), SQLDataType.VARCHAR(12), this, "");

    /**
     * The column <code>public.staffs.user_snils</code>.
     */
    public final TableField<StaffsRecord, String> USER_SNILS = createField(DSL.name("user_snils"), SQLDataType.VARCHAR(14), this, "");

    /**
     * The column <code>public.staffs.owner_id</code>.
     */
    public final TableField<StaffsRecord, UUID> OWNER_ID = createField(DSL.name("owner_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.staffs.created_at</code>.
     */
    public final TableField<StaffsRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    /**
     * The column <code>public.staffs.updated_at</code>.
     */
    public final TableField<StaffsRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "");

    private Staffs(Name alias, Table<StaffsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Staffs(Name alias, Table<StaffsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.staffs</code> table reference
     */
    public Staffs(String alias) {
        this(DSL.name(alias), STAFFS);
    }

    /**
     * Create an aliased <code>public.staffs</code> table reference
     */
    public Staffs(Name alias) {
        this(alias, STAFFS);
    }

    /**
     * Create a <code>public.staffs</code> table reference
     */
    public Staffs() {
        this(DSL.name("staffs"), null);
    }

    public <O extends Record> Staffs(Table<O> path, ForeignKey<O, StaffsRecord> childPath, InverseForeignKey<O, StaffsRecord> parentPath) {
        super(path, childPath, parentPath, STAFFS);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StaffsPath extends Staffs implements Path<StaffsRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StaffsPath(Table<O> path, ForeignKey<O, StaffsRecord> childPath, InverseForeignKey<O, StaffsRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StaffsPath(Name alias, Table<StaffsRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StaffsPath as(String alias) {
            return new StaffsPath(DSL.name(alias), this);
        }

        @Override
        public StaffsPath as(Name alias) {
            return new StaffsPath(alias, this);
        }

        @Override
        public StaffsPath as(Table<?> alias) {
            return new StaffsPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StaffsRecord> getPrimaryKey() {
        return Keys.STAFFS_PKEY;
    }

    @Override
    public List<ForeignKey<StaffsRecord, ?>> getReferences() {
        return Arrays.asList(Keys.STAFFS__STAFFS_OWNER_ID_FKEY, Keys.STAFFS__STAFFS_USER_ID_FKEY);
    }

    private transient OwnersPath _owners;

    /**
     * Get the implicit join path to the <code>public.owners</code> table.
     */
    public OwnersPath owners() {
        if (_owners == null)
            _owners = new OwnersPath(this, Keys.STAFFS__STAFFS_OWNER_ID_FKEY, null);

        return _owners;
    }

    private transient UsersPath _users;

    /**
     * Get the implicit join path to the <code>public.users</code> table.
     */
    public UsersPath users() {
        if (_users == null)
            _users = new UsersPath(this, Keys.STAFFS__STAFFS_USER_ID_FKEY, null);

        return _users;
    }

    @Override
    public Staffs as(String alias) {
        return new Staffs(DSL.name(alias), this);
    }

    @Override
    public Staffs as(Name alias) {
        return new Staffs(alias, this);
    }

    @Override
    public Staffs as(Table<?> alias) {
        return new Staffs(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Staffs rename(String name) {
        return new Staffs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Staffs rename(Name name) {
        return new Staffs(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Staffs rename(Table<?> name) {
        return new Staffs(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Staffs where(Condition condition) {
        return new Staffs(getQualifiedName(), aliased() ? this : null, null, Internal.condition(this, condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Staffs where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Staffs where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Staffs where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Staffs where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Staffs where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Staffs where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Staffs where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Staffs whereExists(TableLike<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Staffs whereNotExists(TableLike<?> select) {
        return where(DSL.notExists(select));
    }
}
